version: '3'

services:
  php:
    container_name: setup-php-gymflow
    build:
      context: ./Docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./Api:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - '9003:9000'
    expose:
      - '9003'
    networks:
      - setup-network

  nginx:
    container_name: setup-nginx-gymflow
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '4444:443'
    volumes:
      - ./Api:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-network

  mysql:
    container_name: setup-mysql-gymflow
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-network
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: gymflow_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    container_name: setup-redis-gymflow
    build:
      context: ./Docker/redis
      dockerfile: Dockerfile
    ports:
      - '6381:6379'

networks:
  setup-network:
    driver: bridge


volumes:
  setup-data:
    driver: local